### ISSUE TITLE
options and arrays

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli-packages#30]
What if I have a flag that's an array, but has enumerated options.  Example from ui-api
`    layouttypes: flags.array({char: 'l', options: ['Compact', 'Full'], description: 'which layout' }),`
https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_resources_record_ui.htm

This throws an error if the array isn't exactly 1 of those types.  Could arrays validate instead that all the members of the array are members of the options?

**Comment by rbergman** [comment]
That's a good observation, and I agree it would make more sense to handle it as you suggest.  `options` is handled at a deeper level in oclif's flag processor (which we extend).  We may be able to intercept and remove that flag, though, and then apply our own logic in the array parser.  It's worth considering this one to be a legit a bug, IMO.

**Comment by rbergman** [comment]
Until fixed, you could write a custom parser that handles this case using `flags.option`.
