### ISSUE TITLE
"The ReportFolder named <> was not found in the workspace"

### ISSUE THREAD

**Issue by gsbasso** [forcedotcom/cli-packages#38]
### Summary

Attempting to deploy report using force:source:deploy -x package.xml

### Steps To Reproduce:
<ol>
<li>Create a report folder MyReportFolder</li>
<li>Create a simple report MyReport and save under MyReportFolder</li>
<li>Create a package.xml file that includes the following content:</li>
<pre>
&lt;types&gt;
    &lt;members&gt;MyReportFolder/MyReport&lt;/members&gt;
    &lt;name&gt;Report&lt;/name&gt;
&lt;/types&gt;
</pre>
<li>Run sfdx command:</li>
<pre>sfdx force:source:deploy -x package.xml</pre>
</ol>

### Expected result

Report should be created/updated in target instance

### Actual result

The following error message is returned:
<pre>The ReportFolder named MyReportFolder/MyReport was not found in the workspace.</pre>

### Additional information

Replacing the forward-slash in the report path with a backward-slash fixes the problem, as in:
<pre>
&lt;types&gt;
    &lt;members&gt;MyReportFolder\MyReport&lt;/members&gt;
    &lt;name&gt;Report&lt;/name&gt;
&lt;/types&gt;
</pre>

**SFDX CLI Version**:
(sfdx --version) sfdx-cli/6.48.0-bfccc40118 (windows-x64) node-v8.9.4
(sfdx force --version) v44.0

**OS and version**:
Windows 7 64-bit

**Comment by gsbasso** [comment]
Apologies - I reported this issue with the mistaken impression this project was for the **core** sfdx cli.

**Comment by dcarroll** [comment]
Will you re-report the issue there?

**Comment by gsbasso** [comment]
I will/would if there is a project for the **core** sfdx cli? Is there one?
