### ISSUE TITLE
Response time is very slow for any sfdx command

### ISSUE THREAD

**Issue by sanketadi** [forcedotcom/cli-packages#40]
### Summary

I am using Salesforce CLI and Visual studio code for Salesforce DX. The command prompt is taking very long time to execute the sfdx command.
Is this because the system configuration which I am using or some other parameters plays role here?

### Steps To Reproduce:

1.  Open the command prompt
1.  type sfdx command and enter

### Expected result

It should have executed fast. 
### Actual result

I have to wait almost for 5 minutes or even more than that. many a time it results in Etimedout error.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**:
44.14.0

**OS and version**:
Ram memory 4GB
32 bit operating system
Window 7

**Comment by clairebianchi** [comment]
@sanketadi Yes this is due to your system configuration. We recommend 8GB of Ram or higher.
