### ISSUE TITLE
exclusive/depends on don't work well with default

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli-packages#44]
### Summary

if I set a default on a flag, the parser is acting like it's been set by the user (interfering with exclusive/dependsOn properties.

### Steps To Reproduce:

```
protected static flagsConfig = {
    object: flags.string({char: 'o', description: 'what object to check perms on', required: true}),
    field: flags.string({char: 'f', description: 'what field to check'}),
    profiles: flags.boolean({description: 'return names/ids of profiles'}),
    permsets: flags.boolean({description: 'return names/ids of permission sets'}),
    users: flags.boolean({description: 'return names/ids of users with those profiles and/or permission sets', exclusive: ['permsets', 'profiles']}),
    fieldlevel: flags.string({description: 'what level of perms are you looking for', default: 'Read', options: ['Read', 'Edit'], dependsOn: ['field']}),
    objectlevel: flags.string({description: 'what level of perms are you looking for', default: 'Read', options: ['Read', 'Edit', 'Create', 'Delete', 'ViewAll', 'ModifyAll'], exclusive: ['field']})
  };
```

In this example, if I **don't** specify a value for objectlevel, because it has a default, I'm getting an error thrown

`$ sfdx shane:permset:check -o Project__c -u platformers --field Due_Date__c --fieldlevel Edit --profiles --permsets`
`ERROR running PermCheck:  --field= cannot also be provided when using --objectlevel=`

### Expected result

don't enforce the exclusive unless I'm actually providing a value

### Actual result

exclusive and dependsOn are enforced

**SFDX CLI Version**:
sfdx-cli/6.53.0 (darwin-x64) node-v11.7.0

**OS and version**:
macOS/Mojave 10.14.3

**Comment by tnoonan-salesforce** [comment]
@mshanemc Can you post this issue at the oclif site? We just inherit this behavior. 

https://github.com/oclif/oclif

**Comment by mshanemc** [comment]
will do @tnoonan-salesforce
